language: node_js

node_js: node

install:
  - npm install

script:
  - node build.js
  - cp -r assets build/assets

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
